[
    {
        "Course_Name": "Data Analytics for Civil Engineers SS24",
        "Course_id": "37383",
        "Forums": [
            [
                {
                    "Forum_name": "Ankündigungen",
                    "Forum_id": "1757385",
                    "Discussions": [
                        {
                            "Discussion_Name": "Online Support Session Today",
                            "Discussion_Id": "606849",
                            "Messages": [
                                {
                                    "Message_id": "p1088425",
                                    "Author": "Mohamed Abdelfattah",
                                    "DateTime": "2024-07-10T11:34:38+02:00",
                                    "Content": "Dear all, Due to the weather condition, I offer today’s support session online during the usual time: 14:15-15:45.  Here is the link for the session: https://bbb.innocampus.tu-berlin.de/rooms/abd-aay-jxc-8zw/join  Best regards, Mohamed",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Group Peer Review work",
                            "Discussion_Id": "606552",
                            "Messages": [
                                {
                                    "Message_id": "p1087998",
                                    "Author": "Mohamed Abdelfattah",
                                    "DateTime": "2024-07-09T11:39:39+02:00",
                                    "Content": "Dear all, As we have received multiple complains from students about group members not contributing, we will have a peer review survery after the challenge next week where everyone can evaluate each teammate's participation in the group, which will be anonymous of course.  If you would like to document this, please add details in the survey when it's released, which will be taken into account for the grades!  We advise you now to continue working and focusing on your challenge with the current situation. Best regards, Mohamed ",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Final Challenge",
                            "Discussion_Id": "600839",
                            "Messages": [
                                {
                                    "Message_id": "p1079791",
                                    "Author": "Mohamed Abdelfattah",
                                    "DateTime": "2024-06-13T12:26:48+02:00",
                                    "Content": "Dear all, The final group challenge is now online. I highly advise you to start working as soon as possible and to work as a team! Best regards, Mo",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Grades for the first project",
                            "Discussion_Id": "595437",
                            "Messages": [
                                {
                                    "Message_id": "p1071746",
                                    "Author": "Mohamed Abdelfattah",
                                    "DateTime": "2024-05-20T13:33:25+02:00",
                                    "Content": "Dear all, The grades for the first project (Neural Networks) are now published.   Good luck! Mo",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Final Groups Created",
                            "Discussion_Id": "593106",
                            "Messages": [
                                {
                                    "Message_id": "p1068000",
                                    "Author": "Mohamed Abdelfattah",
                                    "DateTime": "2024-05-07T20:05:13+02:00",
                                    "Content": "Dear all, The groups for the final project are now created for those who answered the survey as promised. You can find the created groups in the final challenge part on ISIS. Please get to know your group members early on.  We wish you the best of luck! Mo",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Welcome &amp; Registration for the final group project",
                            "Discussion_Id": "586920",
                            "Messages": [
                                {
                                    "Message_id": "p1058396",
                                    "Author": "Mohamed Abdelfattah",
                                    "DateTime": "2024-04-17T14:38:32+02:00",
                                    "Content": "Dear all, Welcome to our Data Analytics for Civil Engineers module. I hope you enjoyed the first lecture. You will find all projects now with their submission deadlines on ISIS except the final group challenge which will be posted down the road. Please don't hesitate to come to support sessions Mondays and Wednesdays (14:00 to 16:00) if you have any question regarding your projects.  As discussed in the first lecture (yesterday), please answer the survey about whether you would like to participate in the final group project. You have until 30.04.2024 to register so that we can assign you all to groups early on. You can find the survey here as well: https://isis.tu-berlin.de/mod/choice/view.php?id=1818124. Best regards, Mo",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        }
                    ]
                }
            ],
            [
                {
                    "Forum_name": "General questions and discussions",
                    "Forum_id": "1759464",
                    "Discussions": [
                        {
                            "Discussion_Name": "Group B",
                            "Discussion_Id": "602325",
                            "Messages": [
                                {
                                    "Message_id": "p1081898",
                                    "Author": "Mohammed Shakker Usman",
                                    "DateTime": "2024-06-20T11:08:44+02:00",
                                    "Content": "Hey Group B members,  We have created a Whatsapp group so that you guys can join. The link is provided below.   https://chat.whatsapp.com/BVXDpVOYQto9KUqLj03b8j  Hope to hear from you soon. Thanks.",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Group B",
                            "Discussion_Id": "601634",
                            "Messages": [
                                {
                                    "Message_id": "p1080956",
                                    "Author": "Mohammed Shakker Usman",
                                    "DateTime": "2024-06-17T20:04:40+02:00",
                                    "Content": "Hi Group B members,  I am Mohmmed Shakker Usman. This is my whatsapp number: +4917672485861, Hope to hear from you guys soon.",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Group E",
                            "Discussion_Id": "601432",
                            "Messages": [
                                {
                                    "Message_id": "p1080649",
                                    "Author": "Vincent Fredrik Mayer",
                                    "DateTime": "2024-06-17T11:21:52+02:00",
                                    "Content": "Hello Group E,  I have set up a WhatsApp group for us. Feel free to use the link to join the group!  https://chat.whatsapp.com/Ft1T6jFsTjjIkuTzWFl8o7  Best regards, Vincent",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Group A",
                            "Discussion_Id": "601187",
                            "Messages": [
                                {
                                    "Message_id": "p1080289",
                                    "Author": "Pengfei Guo",
                                    "DateTime": "2024-06-14T22:20:34+02:00",
                                    "Content": "Hi Group A members, I am Pengfei Guo, my email is chinaguopengfei727@gmail.com and my whatsapp is +49 15754809992. Happy to keep in touch. Best regards, Pengfei Guo",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Unrealistic and Likely False Results-Assignment 4",
                            "Discussion_Id": "598290",
                            "Messages": [
                                {
                                    "Message_id": "p1076073",
                                    "Author": "Tala Ramadan",
                                    "DateTime": "2024-06-02T03:33:56+02:00",
                                    "Content": "Hello everyone, I wanted to reach out regarding an issue I've been encountering recently in Task 2. Despite my best efforts, I've been consistently receiving unrealistic and likely false results when attempting to make predictions using our model on images. Over the past few days, I've dedicated a considerable amount of time to troubleshooting this issue. I've even taken the step of rerunning the model, which fortunately only took around 5.5 hours. Additionally, I tried clearing the values by executing rm(img_tensor) and rm(score), but to no avail. Regardless of the image provided, the model consistently predicts a bulldozer with 100% confidence. Although the score values vary very slightly each time. To ensure accuracy, I rewrote the code manually, hoping to eliminate any potential errors. However, the problem persists. For all following images I got the following prediction result. (I tried even many more)   The results of accurac is very high though, while the loss is low.  I am already sure about overfitting issues in the model but still I was expecting some better predictions.   Furthermore, I've encountered difficulties with the application of the train function. Every attempt results in the same error, hindering our progress.    Has anyone else experienced similar challenges? I would greatly appreciate the opportunity to discuss these errors and results with you. Thank you, and I wish you all the best.",
                                    "Response to": "This is the original post"
                                },
                                {
                                    "Message_id": "p1076670",
                                    "Author": "Abdul Rafay Karim",
                                    "DateTime": "2024-06-03T21:38:32+02:00",
                                    "Content": "Hi Tala, I found this code that is working for the cross validation part. I am not 100% sure since I didn't get improvement cost but I got some results. ctrl <- trainControl(method = \"cv\", number = 5) # Define cross-validation settings  # Replace this with your actual training data set.seed(123) trainData <- data.frame( TOTAL_IMP_COST_096 = factor(sample(1:5, 100, replace = TRUE)), var1 = rnorm(100), var2 = rnorm(100) )  # Define a tuning grid for mtry values tuneGrid <- expand.grid(mtry = 1:5) # Adjust this range based on your dataset  tunedModel <- train( TOTAL_IMP_COST_096 ~ ., data = trainData, method = \"rf\", trControl = ctrl, tuneGrid = tuneGrid )  print(tunedModel)",
                                    "Response to": "p1076073"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Assignment 4 Issues with Data augmentation",
                            "Discussion_Id": "598243",
                            "Messages": [
                                {
                                    "Message_id": "p1076002",
                                    "Author": "Julius Florian Rachlitz",
                                    "DateTime": "2024-05-31T22:57:40+02:00",
                                    "Content": "Hey,  I have issues with the Data augmentation Code:   I tried to write a seperate function, but it did not help. Anyone ecountering the same problem or any ideas how to fix it? Many thanks Julius",
                                    "Response to": "This is the original post"
                                },
                                {
                                    "Message_id": "p1076069",
                                    "Author": "Pengfei Guo",
                                    "DateTime": "2024-06-01T23:33:21+02:00",
                                    "Content": "Same here",
                                    "Response to": "p1076002"
                                },
                                {
                                    "Message_id": "p1076147",
                                    "Author": "Sofia Mari Wilkinson",
                                    "DateTime": "2024-06-02T15:57:41+02:00",
                                    "Content": "I've been stuck on the same error the past few days, I've tried a lot of different things but cannot get past data augmentation.",
                                    "Response to": "p1076002"
                                },
                                {
                                    "Message_id": "p1076151",
                                    "Author": "Sofia Mari Wilkinson",
                                    "DateTime": "2024-06-02T16:23:21+02:00",
                                    "Content": "Update: I was working with Mohamed Tarek because we had similar errors, and we now have a code that seems to be running the epochs. That being said, we unfortunately had to completely rewrite a couple sections...we could not get past data augmentation with the original code.  For those still stuck, you can try substituting the following lines for data augmentation, but please be warned that you might have to change the model training section as well as it was not fully compatible.  # Data augmentation using the functional API input_layer <- layer_input(shape = c(image_size, 3)) output_layer <- input_layer %>% layer_random_flip(\"horizontal\") %>% layer_random_rotation(factor = 0.1) data_augmentation <- keras_model(inputs = input_layer, outputs = output_layer)  (include the par( ) and for loop lines after this)  I hope this helps, at least to get some results that we can begin analyzing and discussing. Best of luck!",
                                    "Response to": "p1076147"
                                },
                                {
                                    "Message_id": "p1076463",
                                    "Author": "Julius Florian Rachlitz",
                                    "DateTime": "2024-06-03T13:54:51+02:00",
                                    "Content": "Nice, thanks a lot. You helped me there alot. It now works :)",
                                    "Response to": "p1076151"
                                },
                                {
                                    "Message_id": "p1076659",
                                    "Author": "Sofia Mari Wilkinson",
                                    "DateTime": "2024-06-03T21:09:09+02:00",
                                    "Content": "Sure thing! But now I can't get the evaluation part to work though haha",
                                    "Response to": "p1076463"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Assignment 4-Issues with the visualization of the dataset",
                            "Discussion_Id": "597794",
                            "Messages": [
                                {
                                    "Message_id": "p1075333",
                                    "Author": "Tala Ramadan",
                                    "DateTime": "2024-05-30T00:20:11+02:00",
                                    "Content": "Hello everyone,  I am having an issue with my code when it comes to visualizing the dataset. I receive the following error message:  The format of the images is .jpg, and I also tried converting all images to .png, but I still encounter the same error. Has anyone faced a similar issue and would be willing to share how they resolved it? Thank you and good luck!",
                                    "Response to": "This is the original post"
                                },
                                {
                                    "Message_id": "p1075489",
                                    "Author": "Tala Ramadan",
                                    "DateTime": "2024-05-30T13:21:04+02:00",
                                    "Content": "Thanks to Ibrahim Yigit Sun, this part is now working, and I wanted to share how in case someone is experiencing similar issues.  Apparently, after extracting the folders from the ZIP file, the ZIP file and the _MACOSX file need to be either relocated or deleted so R can only find the file \"construction_machine\" from the dataset. This worked for me.  I wish you all good luck and great success with this assignment! :)",
                                    "Response to": "p1075333"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "TensorFlow Setup in RStudio for Assignment 2",
                            "Discussion_Id": "595306",
                            "Messages": [
                                {
                                    "Message_id": "p1071499",
                                    "Author": "Mohammed Amir Aziz Khoshnaw",
                                    "DateTime": "2024-05-18T10:20:06+02:00",
                                    "Content": "I hope you're doing well.  I'm having trouble setting up TensorFlow in RStudio for Assignment 2, even though it worked fine for Assignment 1. Here's what I've done so far:  1. Installed the latest versions of R, RStudio, RTools, and Python 3.9. 2. Made sure Python and Git are added to the system PATH. 3. Installed the `reticulate` package and used it to set up Python. 4. Tried to install TensorFlow using `install_tensorflow(envname = \"r-tensorflow\")` in a new R session. 5. Verified the installations by checking versions and running test commands like `tf$version$VERSION` and `tf$constant(\"Hello TensorFlow!\")`.  Despite all this, I keep getting errors saying TensorFlow is not found.",
                                    "Response to": "This is the original post"
                                },
                                {
                                    "Message_id": "p1071617",
                                    "Author": "Abdul Rafay Karim",
                                    "DateTime": "2024-05-19T14:52:43+02:00",
                                    "Content": "Yes I am going through a similar issue. I was able to run the first task of second assignment. But there is one error in second task which is not being resolved. I have gone through all the steps you have mentioned but the error still persists.",
                                    "Response to": "p1071499"
                                },
                                {
                                    "Message_id": "p1071837",
                                    "Author": "Pengfei Guo",
                                    "DateTime": "2024-05-20T20:29:42+02:00",
                                    "Content": "Have you solved the problem yet? My error is like this py_call_impl(callable, call_args$unnamed, call_args$named): ValueError: Exception encountered when calling Rescaling.call().  Attempt to convert a value () with an unsupported type () to a Tensor.  Arguments received by Rescaling.call(): • inputs= I have tried two laptop but no any solutions.",
                                    "Response to": "p1071617"
                                },
                                {
                                    "Message_id": "p1071851",
                                    "Author": "Mohammed Amir Aziz Khoshnaw",
                                    "DateTime": "2024-05-20T22:08:21+02:00",
                                    "Content": "Actually, still struggling with Tensor Flow",
                                    "Response to": "p1071837"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "FIX: RStudio &amp; Tensorflow on Mac (Apple Silicon)",
                            "Discussion_Id": "590935",
                            "Messages": [
                                {
                                    "Message_id": "p1064642",
                                    "Author": "Lupus Siegert",
                                    "DateTime": "2024-04-29T17:09:20+02:00",
                                    "Content": "Hello everyone, I thought I might share this fix to help anyone using a Mac with Apple Silicon chips. In order to get TensorFlow up and running correctly, make sure to specify version 2.14 during the installation like this: install_keras(tensorflow = \"2.14\") Randomly, you might still get this error when trying to run the code: Error in py_call_impl(callable, call_args$unnamed, call_args$named) :    ValueError: All layers added to a Sequential model should have unique names. Name \"dense_1\" is already the name of a layer in this model. Update the `name` argument to pass a unique name. Run `reticulate::py_last_error()` for details. In this case I have found that clearing the environment, selecting all the code and running it again fixes it. As RStudio is eager to use TensorFlow version 2.16 I found that I have to reinstall version 2.14 every time I open it. Hopefully this helps others, and you won't have to spend hours and hours to fix this. Thank you to John who came up with this solution.  Kind regards Lupus",
                                    "Response to": "This is the original post"
                                },
                                {
                                    "Message_id": "p1065218",
                                    "Author": "Julian Wladyslaw Keller",
                                    "DateTime": "2024-04-30T16:49:12+02:00",
                                    "Content": "I get following Error. Does anyone know how to fix it?",
                                    "Response to": "p1064642"
                                },
                                {
                                    "Message_id": "p1066931",
                                    "Author": "Nour Arabi Katibi",
                                    "DateTime": "2024-05-06T01:27:17+02:00",
                                    "Content": "I got the same error",
                                    "Response to": "p1065218"
                                },
                                {
                                    "Message_id": "p1066932",
                                    "Author": "Nour Arabi Katibi",
                                    "DateTime": "2024-05-06T02:01:32+02:00",
                                    "Content": "To fix it try uninstalling Python from your device, as mentioned in the assignment document:  \"Important: Installing tensorflow and keras will install python (miniconda) on your machine. Sometimes pre-installed Python versions on your machine will collide with this installation. If this happens, you can try to uninstall Python from your machine or to make sure that its version is the same as the one installed by tensorflow.\"",
                                    "Response to": "p1065218"
                                },
                                {
                                    "Message_id": "p1068341",
                                    "Author": "Julian Wladyslaw Keller",
                                    "DateTime": "2024-05-08T15:35:49+02:00",
                                    "Content": "which version of python did you install?",
                                    "Response to": "p1066932"
                                },
                                {
                                    "Message_id": "p1068534",
                                    "Author": "Nour Arabi Katibi",
                                    "DateTime": "2024-05-09T00:26:26+02:00",
                                    "Content": "python 3.11",
                                    "Response to": "p1068341"
                                },
                                {
                                    "Message_id": "p1069059",
                                    "Author": "Julius Florian Rachlitz",
                                    "DateTime": "2024-05-11T15:55:59+02:00",
                                    "Content": "It is important to install Python Version 11.x instead of 12.x. It worked for my PC (Windows) only on 11.x, as 12.x is not supported",
                                    "Response to": "p1068341"
                                },
                                {
                                    "Message_id": "p1071570",
                                    "Author": "Nurlan Taghizade",
                                    "DateTime": "2024-05-18T20:42:31+02:00",
                                    "Content": "Hey, how could you solve this problem? l got same error and l have tried to install older versions of R, tensorflow and python, but had no luck.",
                                    "Response to": "p1065218"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Assignment 2 Anomalie images ",
                            "Discussion_Id": "594584",
                            "Messages": [
                                {
                                    "Message_id": "p1070382",
                                    "Author": "Hillary Raiser",
                                    "DateTime": "2024-05-15T11:24:04+02:00",
                                    "Content": "Hey, has anyone been able to get to the last two tasks for the 2 assigment. I keep trying different distance parameters to plot the images, but I can't seem to get a very smooth image as the one given in the first task. Does anyone have any tips on how to set the configurations so that the image actually makes sense to analyse...? Obvioulsy there are certain conclusions that can definitely still be drawn with this image, but i was wondering whether someone else had any other ways of plotting a clear image as the one given to us in the first task. ",
                                    "Response to": "Response to nothing"
                                }
                            ]
                        },
                        {
                            "Discussion_Name": "Tensorflow &amp; Keras problem",
                            "Discussion_Id": "593640",
                            "Messages": [
                                {
                                    "Message_id": "p1068859",
                                    "Author": "Eisa Sabahi",
                                    "DateTime": "2024-05-10T13:10:43+02:00",
                                    "Content": "Hi there,  I still having problem with running the Tensorflow and Keras,  keras sequential model. I wanted to know is there anyone of you that has managed to do the analysis and is confident enough to explain it to me?? Because I already tried hundreds of ways and still it is not working!  Wish you lock with the assignments",
                                    "Response to": "This is the original post"
                                },
                                {
                                    "Message_id": "p1069058",
                                    "Author": "Julian Wladyslaw Keller",
                                    "DateTime": "2024-05-11T15:31:57+02:00",
                                    "Content": "I also still have not found a solution for my pc. Today I was informed that you can use https://posit.cloud/ for the first assignment.",
                                    "Response to": "p1068859"
                                }
                            ]
                        }
                    ]
                }
            ]
        ]
    }
]